CREATE TABLE users 
(id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
 username VARCHAR(250) NOT NULL UNIQUE,
 password_digest VARCHAR(100) NOT NULL,
 created_at TIMESTAMP DEFAULT NOW(),
 updated_at TIMESTAMP);
